version: '3'
services:
  jasmin:
    image: alinity/bare-jasmin:latest
    ports:
      - 1401:1401
      - 2775:2775
      - 8990:8990
    networks:
      - jasmin-net
    volumes: 
      - jasmin-logs/:/var/log/jasmin/
      - jasmin-data/:/etc/jasmin/
      - jasmin-store/:/etc/jasmin/store/
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.8-management-alpine
    ports:
      - 15672:15672
    hostname: rabbitmq
    networks: 
      - jasmin-net
    volumes:
    - rabbitmq-etc/:/etc/rabbitmq/
    - rabbitmq-data/:/var/lib/rabbitmq/
    - rabbitmq-logs/:/var/log/rabbitmq/

  redis:
    image: redis:6.0.8-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - jasmin-net
    volumes:
      - redis-data:/data

networks:
  jasmin-net:

volumes:
  redis-data:
  rabbitmq-etc:
  rabbitmq-data:
  rabbitmq-logs:
  jasmin-logs:
  jasmin-data:
  jasmin-store: