version: '3'
services:
  jasmin:
    image: alinity/bare-jasmin:latest
    ports:
      - 1401:1401
      - 2775:2775
      - 8990:8990
    networks:
      - jasmin-net
    volumes: 
      - jasmin-data/logs/:/var/log/jasmin/
      - jasmin-data/jasmin/:/etc/jasmin/
      - jasmin-data/store/:/etc/jasmin/store/
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.8-management-alpine
    hostname: rabbitmq
    networks: 
      - jasmin-net
    volumes:
    - rabbitmq-data/etc/:/etc/rabbitmq/
    - rabbitmq-data/data/:/var/lib/rabbitmq/
    - rabbitmq-data/logs/:/var/log/rabbitmq/

  redis:
    image: redis:6.0.8-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - jasmin-net
    volumes:
      - redis-data:/data

networks:
  jasmin-net:

volumes:
  redis-data:
  rabbitmq-data:
  jasmin-data: